### ISSUE TITLE
Cloud CPM not booting on real hardware

### ISSUE THREAD

**Issue by arcadeshopper** [DJSures/NABU-Internet-Adapter#1]
this worked a week ago, now giving ERROR #D after BIOS starts on real NABU
![rn_image_picker_lib_temp_f217638e-ce78-4129-824a-d5ff2ef36507](https://user-images.githubusercontent.com/34459018/213491303-754c6a92-211d-40e6-8911-e18941e67cc5.jpg)
network adapter version Version 2023.01.18.00 running on linux 
also reported on windows from other users
unable to duplicate on MAME works fine there

**Comment by timw4mail** [comment]
Also an issue on real hardware: RetroNet and CP/M toggle off RF output with a click of the RF relay. 

I did see Error #D on Linux as well, but on Windows with the default baud and 0 delay, it worked fine.

**Comment by gtampdotcom** [comment]
Are stop bits set to 2?

**Comment by arcadeshopper** [comment]
there is nowhere to set stop bits in the linux client

**Comment by DJSures** [comment]
![image](https://user-images.githubusercontent.com/49293683/213626243-0918d784-d6ee-4ef1-b4af-e9f60e03bc1d.png)

**Comment by DJSures** [comment]
Try the latest cpm - it might help with the linux baudrate. "might" or "should"

**Comment by arcadeshopper** [comment]
boots now and works great currently in retronet.. thank you!
