### ISSUE TITLE
NABU machine not booting

### ISSUE THREAD

**Issue by kpishere** [DJSures/NABU-Internet-Adapter#13]
DJSures : 

Not sure what the problem is here.  Data appears to be getting to the Nabu, below is a picture of the interactions to it getting the first chunk of data.  My bios rom has a label showing '90020060 REV A'.

The screen is simply blue, no text.  Here is a capture of the data on the RS422 line .. 

![Screen Shot 2023-03-27 at 6 42 21 PM](https://user-images.githubusercontent.com/25204173/228083216-da31a0d1-300c-4f26-ab29-c1f60d011e42.png)

A little later, it appears to re-try? 

![Screen Shot 2023-03-27 at 6 43 20 PM](https://user-images.githubusercontent.com/25204173/228083341-4015f22b-7627-4fec-a7c8-45724f8bf4b9.png)

But then it changes .. 

![Screen Shot 2023-03-27 at 6 44 20 PM](https://user-images.githubusercontent.com/25204173/228083428-95fb41f7-fd0e-4a46-ba9a-2f72aaee1e70.png)

And ends here ...

![Screen Shot 2023-03-27 at 6 45 16 PM](https://user-images.githubusercontent.com/25204173/228083582-1b5c5655-5f3d-4da6-9521-a7e016b78130.png)

**Comment by DJSures** [comment]
sorry, i don't know what this is

**Comment by kpishere** [comment]
I'll get a scope and then logic analyzer on the RS422 wires to verify signal integrity.  Otherwise, could it be the BIOS?  Or is that confirmed to be a good version, '90020060 REV A'

I'm using one of these devices I happen to have, 'MHS100650 COM2 Model: IP921 ROUTER' which gives me TCP over ethernet/wifi to RS422 connection.  They are commonly used in traffic light control systems and other industrial stuff.
