### ISSUE TITLE
NABU_Internet_Adapter_84 - Ubuntu 22.04.1 LTS - NullReferenceException

### ISSUE THREAD

**Issue by marknmel** [DJSures/NABU-Internet-Adapter#2]
Hi DJ - thanks for the YouTube videos and the NABU revival. Fun stuff.

I'm getting an abort (NullReferenceException) with the NABU_Internet_Adapter_84 (downloaded today, Jan 19, 2023)
My Linux is Ubuntu 22.04.1 LTS.

Here's what happens:

```
mark@mark-Aspire-V5-571P:~/Downloads/NABU-RetroNet/linux-x64$ ls -l
total 18464
-rw-rw-r-- 1 mark mark    24120 Oct 18 09:00 libSystem.IO.Ports.Native.so
-rwxrwxr-x 1 mark mark 18880112 Jan 18 13:57 NABU-Internet-Adapter-84
mark@mark-Aspire-V5-571P:~/Downloads/NABU-RetroNet/linux-x64$ sudo ./NABU-Internet-Adapter-84 
[sudo] password for mark: 
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Unix.Terminal.Curses.endwin()
   at Terminal.Gui.CursesDriver.End()
   at Terminal.Gui.Application.ResetState()
   at Terminal.Gui.Application.Shutdown()
   at NABU_Internet_Adapter_84.Program.Main(String[])
Aborted

```

It aborts just about immediately.  I get no window or anything like that.

I took a look with ldd to see if I was missing something, and it seemed OK to me.
I also used strace to follow the system calls. I couldn't tease out anything interesting.

Any ideas?
Thanks!
/Mark

**Comment by DJSures** [comment]
looks like trouble with ncurses. make sure you have ncurses. and make sure you are also executing the correct binary for your OS. there's ppl trying to run the wrong binaries and having issues because the libraries aren't compatible across different word sizes and cpus. i also saw someone in the discord a while ago mention they needed to make a symbolic link for a linux distro. you could go on there and ask if anyone remembers what the symbolic link was all about - could be that too

**Comment by marknmel** [comment]
Hey DJ, thanks for the response.

I can confirm I have x86_64 binaries and a platform that matches.

I agree it looks like ncurses. That's what I thought too.  I confirmed that I had the ncurses packages installed.

```
mark@mark-Aspire-V5-571P:~/mame/mame-nabupc_wip$ apt search ncurses | grep "^ncurses"

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


ncurses-base/jammy,jammy,now 6.3-2 all [installed]
ncurses-bin/jammy,now 6.3-2 amd64 [installed]
ncurses-doc/jammy,jammy 6.3-2 all
ncurses-examples/jammy 6.3-2 amd64
ncurses-hexedit/jammy,now 0.9.7+orig-7.1 amd64 [installed]
ncurses-term/jammy,jammy,now 6.3-2 all [installed]
```
I can ask around on discord (I've not been there before - living under a rock I guess...). 

Any other means to debug this?  Logging?

Thanks again
/Mark

**Comment by ayourk** [comment]
I'm having the same issue.  I have ncurses 5 and 6 installed on my 22.04.1 Ubuntu.  Apparently  20.04.5 Ubuntu has no problems.
More info:
uname -a: `Linux Z590-P 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
file NABU-Internet-Adapter-84: `NABU-Internet-Adapter-84: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=751599590dc5bab2aaa23d5e8e800083dee162a5, not stripped, too many notes (256)`
ldd NABU-Internet-Adapter-84: 
```
        linux-vdso.so.1 (0x00007ffc0f8ef000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x000014f0a9102000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000014f0a90fd000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x000014f0a90e1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000014f0a8ffa000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x000014f0a8ff5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000014f0a8fd3000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x000014f0a8da9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000014f0a8b81000)
        /lib64/ld-linux-x86-64.so.2 (0x000014f0a9bef000)
```
dpkg -l | fgrep curse:
```
ii libncurses-dev:amd64 6.3-2 amd64 developer's libraries for ncurses
ii libncurses5:amd64 6.3-2 amd64 shared libraries for terminal handling (legacy version)
ii libncurses5-dev:amd64 6.3-2 amd64 transitional package for libncurses-dev
ii libncurses6:amd64 6.3-2 amd64 shared libraries for terminal handling
ii libncurses6:i386 6.3-2 i386 shared libraries for terminal handling
ii libncursesw6:amd64 6.3-2 amd64 shared libraries for terminal handling (wide character support)
ii libncursesw6:i386 6.3-2 i386 shared libraries for terminal handling (wide character support)
ii libtinfo-dev:amd64 6.3-2 amd64 transitional package for libncurses-dev
ii mtr-tiny 0.95-1 amd64 Full screen ncurses traceroute tool
ii ncdu 1.15.1-1 amd64 ncurses disk usage viewer
ii ncurses-base 6.3-2 all basic terminal type definitions
ii ncurses-bin 6.3-2 amd64 terminal-related programs and man pages
ii ncurses-term 6.3-2 all additional terminal type definitions
ii pinentry-curses 1.1.1-1build2 amd64 curses-based PIN or pass-phrase entry dialog for GnuPG
```
Please let me know if I'm missing anything important.

**Comment by marknmel** [comment]
Thanks @ayourk  - I thought I was crazy.  There is a bunch of nice folks over in the NABU discord channel chiming in.  If I learn something - I'll post back here.

**Comment by arcadeshopper** [comment]
from jefferystone on discord
Create this link in the folder where the NABU-Internet-Adapter-84 is:

cd /path/to/NABU-Internet-Adapter-84

ln -s /lib/x86_64-linux-gnu/libdl.so.2 libdl.so

---

Long listing shows the symlink:

ls -l libdl.so

libdl.so -> /lib/x86_64-linux-gnu/libdl.so.2

**Comment by marknmel** [comment]
That did it.  Thank you very much!

**Comment by DJSures** [comment]
thanks everyone - great contribution! I'll add this to nabu.ca internet adapter download so people know what to look for in the future
