### ISSUE TITLE
Cloud CP/M BIOS 3.1b is slow, drops characters (MAME)

### ISSUE THREAD

**Issue by GryBsh** [DJSures/NABU-Internet-Adapter#4]
2.9 was speedy and didn't exhibit dropped characters in telnet, 3.1 is much slower and drops characters:
![image](https://user-images.githubusercontent.com/120699894/217518551-1e9169dd-c9e0-4d72-855d-58e869476add.png)

Latest IA, all default settings.

**Comment by DJSures** [comment]
Hmmm interesting! Let me take a look at that and fix it for ya tonight! Thanks for letting me know

**Comment by DJSures** [comment]
3.2b is online - sorry about the trouble. I was trying to optimize a few things the other day and forgot to renable an interrupt when processing the vt52. 

```
/// **************************************************************************************************
// 4 Console OUTput
/// **************************************************************************************************
void doConout() __naked {

  __asm;

    di;

    ld a, c;
    ld (__A), a;

    SAVE_STACK_ASM

    ei; <--- THIS

  __endasm;

    doVT(_A);

  __asm

    di; <--- AND THIS

    RESTORE_STACK_ASM

    ei;

    ret;

  __endasm;
}
```

**Comment by GryBsh** [comment]
Oh ya, night and day difference. I'd call that fixed for sure. thanks. :)
