### ISSUE TITLE
Cloud CP/M A0:SX2.COM, "man" command not working (missing file)

### ISSUE THREAD

**Issue by jefferystone** [DJSures/NABU-Internet-Adapter#5]
Using NABU IA 2023.02.06.00 

Please let me know if Cloud CP/M structure/files missing issues belong in some other place.

On Cloud CP/M, A0:SX2.COM has a "man" command (stands for manual) that helps you look up command usage.

For this to work, you need A0:SAMARUX.MAN

This can be downloaded from:  https://github.com/MiguelVis/samarux/blob/master/samarux.man  (use the RAW button and copy/paste to sarmarux.man).

Before:
![sx2_man_error](https://user-images.githubusercontent.com/7465088/217549345-14ea5ce2-ff59-4a4c-a7ca-438aa323858d.png)

If using file on B0:SAMARUX.MAN and using the below command it works, but is should work as:  man ls

![sx2_man_bdrive_ok](https://user-images.githubusercontent.com/7465088/217551048-a4ade324-f54c-4d4b-98db-1d8e807c0104.png)

**Comment by DJSures** [comment]
Will do!

**Comment by DJSures** [comment]
Done! Thanks

![image](https://user-images.githubusercontent.com/49293683/217723203-d1aa69c2-9a02-4c10-ab57-700051d47f91.png)
