### ISSUE TITLE
cloud cpm telnet won't do any other port but 23

### ISSUE THREAD

**Issue by arcadeshopper** [DJSures/NABU-Internet-Adapter#6]
cpm telnet not allowing port selection only does port 23

**Comment by DJSures** [comment]
Got it - gimme a few min i'll fix it in a bit

**Comment by DJSures** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/49293683/219499286-00b720b1-38f0-4296-a2f5-9ad49ba1b3b8.png)

**Comment by arcadeshopper** [comment]
Thanks!
