### ISSUE TITLE
User 10 and up showing single ascii char instead of double digits

### ISSUE THREAD

**Issue by jefferystone** [DJSures/NABU-Internet-Adapter#7]
"user number" is showing single ASCII character so after 9 gives:

User | Dec | Hex | Char | Desc
   9    |  57  | 39   |    9    | Nine
  10   |  58  | 3A  |     :     | Colon
  11   |  59  | 3B  |     ;     | Semicolon
  12   |  60  | 3C  |    <    | Less than
  13   | 61   | 3D  |    =    | Equality sign
  14   | 62   | 3E  |    >    | Greater than
  15   | 63   | 3F  |    ?    | Question mark

user 13:  A:=>
user 11:  A:;>

**Comment by DJSures** [comment]
Haha yeah - I've been putting off fixing that because it requires an update to the boot loader because it'll shift the size of the ccp in the cpm load. I'll tackle this simultaneously when I have a big enough change that will include other things. :) I Hope you can live with it for a bit longer.

**Comment by jefferystone** [comment]
Not a problem - just didn't know if it recently regressed or not.

**Comment by jefferystone** [comment]
Does this affect rncmd for user numbers 10 and up?

**Comment by DJSures** [comment]
nope - it'll only matter for displaying the double digit user number. it's because after the digit 9 is the digits : ; < =  > etc...

**Comment by DJSures** [comment]
fixed
