### ISSUE TITLE
RS422 Alternative no longer working

### ISSUE THREAD

**Issue by leonkiriliuk** [DJSures/NABU-Internet-Adapter#8]
I recently built the RS422 alternative method of connecting the NABU to a PC (I find all adapters in the computer to be a cleaner solution)

I was surprised by a comment left here: https://github.com/Kris-Sekula/NABU/tree/main/RS422Alternative

“ It works! ... well it "worked"...fine with the first version of the Nabu software, but now something has changed... so this adapter only works with the alternative "monitor" that I tested ...”

I tested it with latest version of the adapter on Windows, OSX and all show the same problem. The software sees the com port, initializes it but then just sits there. Doesn’t do anything. When I pull the USB cable out of the PC, the software detects the port is gone and turns off the emulator. 

Is this something that can be fixed?

**Comment by masto** [comment]
I figured out what the problem is. The COM port is being configured with RTS/CTS flow control, so no data ever gets transmitted. Here's a video I made explaining it: https://youtu.be/PYC9fdRiZhA

I would imagine the fix is trivial (set no flow control).

**Comment by masto** [comment]
@leonkiriliuk You may be able to confirm this on your adapter by grounding CTS.

**Comment by DJSures** [comment]
Ah i see - I'll add an option in the internet adapter for you. Stay tuned

**Comment by leonkiriliuk** [comment]
Any luck? It seems other people are tripping on the same problem using RS422 adapters that are different from the one used to develop the software.

**Comment by DJSures** [comment]
yeah i had a few other things to finish before I can push it out. i can do it tonight

**Comment by DJSures** [comment]
sorry i'm a bit delayed because the build server I use from our office is down for maintenance. it has the code sign cert and installer, etc... so I'll have to wait a few days until they get it back up

**Comment by DJSures** [comment]
looks like it'll be back up this evening - so I can push a release for you to fix this. stay tuned

**Comment by DJSures** [comment]
Fixed!
